apiVersion: v1
kind: Service
metadata:
  name: {{ template "webapp.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ template "webapp.name" . }}
    release: {{ .Release.Name }}
  ports:
{{- range $port := .Values.service.ports }}  
  - protocol: {{ $port.protocol | quote }}
    port: {{ $port.containerPort }}
    targetPort: {{ $port.containerPort }}
{{- end }}    
  type: ClusterIP
