apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoiz-web
  namespace: invoiz-production
  labels:
    app: invoiz-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: invoiz-web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 30
  template:
    metadata:
      labels:
        app: invoiz-web
    spec:
      containers:
      - name: invoiz-web
        image: invoiz-dr.deltra.de:5000/invoiz/web:v__TFS_BUILD_NUMBER__
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          protocol: TCP
        env:
          - name: TFS_BUILD_NUMBER
            value: "__TFS_BUILD_NUMBER__"
      nodeSelector:
        node: prod
