apiVersion: v1
appVersion: "1.0"
description: A Helm chart for imprezz-webapp Kubernetes deployment
name: webapp
version: 0.1.0
engine: gotpl
home: http://tfs:8080/tfs/Buhl%20Entwicklung/INVOIZ/_dashboards
icon: https://invoiz-admin.buhl.de/assets/images/svg/invoiz.svg
sources:
  - http://tfs:8080/tfs/Buhl%20Entwicklung/INVOIZ/_git/api
maintainers:
  - name: Satish Verma
    email: satish.verma@empower-solutions.co.in
