releaseEnvironment: dev
image:
  repository: registry.sw.buhl-data.com/imprezz/webapp
  tag: v0.0.1
  pullPolicy: Always

service:
  type: ClusterIP
  ports:
    - name: "api-tcp-port"
      protocol: TCP
      containerPort: 80

replicaCount: 1
